auto: true
markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title

var:
  about_path: /about
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  search_path : /search.html
  bucket_list: /bucket.html

author :
  name : Hendriono
  email : hendriono@gmail.com
  github : hendriono
  disqus_shortname: hendgithub
  twitter : dedehendriono

production_url : http://hendriono.github.com
maintitle: "Kyll BloGit"
description: "Kyll BloGit membahas tentang Jekyll, GitHub dan hal-hal yang terkait dengan keduanya"